	PlotHeight2 = 10;
	PlotScale = 5;
	setf(PlotMode,PL_BENCHMARK);
	// plot("EMA_L", EMA_L, LINE, YELLOW);
	// plot("EMA_H", EMA_H, LINE, MAGENTA);
	plot("HH", HH(TimePeriod,1), LINE, BLACK);
	plot("LL", LL(TimePeriod,1), LINE, BLACK);
	plot("c1", s1, NEW|LINE, GREY);
	plot("c2", s2, NEW|LINE, GREY);
	plot("c3", s3, NEW|LINE, GREY);
	plot("c4", s4, NEW|LINE, GREY);
